# -*- coding: utf-8 -*-
"""ПМО.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UynCSbuVARWmOwRFXBfv6gz22MDwQG0v
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import shapiro

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.metrics import silhouette_score
from sklearn.metrics import calinski_harabasz_score
from sklearn.metrics import davies_bouldin_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import export_graphviz
import graphviz
# Датасет должен лежать в папке data/ (см. README.md)

df = pd.read_csv('data/StudentPerformanceFactors.csv')

df

"""Этот набор данных содержит информацию об академической успеваемости, образе жизни и социально-экономических факторах, связанных со студентами, в том числе об их результатах на экзаменах.

Он включает в себя данные о времени, потраченном на учебу, посещаемости, продолжительности сна, мотивации, дополнительных занятиях, участии родителей, типе учебного заведения и других факторах окружающей среды.

Целевой переменной является Exam_Score, которая отражает итоговую оценку студента на экзамене

'Hours_Studied' - часы обучения (количественная)

'Attendance' - Посещаемость (количественная)

'Parental_Involvement' - «Участие родителей»  (категориальная Medium, High, Low)

'Access_to_Resources' - «Доступ к ресурсам» (категориальная Medium, High, Low)

'Extracurricular_Activities' - «Внеклассные мероприятия» (категориальная YES, NO)

'Sleep_Hours', - «Часы сна» (количественная)

'Previous_Scores' - «Предыдущие оценки» (количественная)
       
'Motivation_Level' - «Уровень мотивации» (категориальная Medium, High, Low)

'Internet_Access', - «Доступ к интернету» (категориальная YES, NO)

'Tutoring_Sessions' - «Репетиторские занятия» (количественная)

'Family_Income', - «Доход семьи» (категориальная Medium, High, Low)

'Teacher_Quality' - «Квалификация учителя» (категориальная Medium, High, Low)

'School_Type', - «Тип школы» (категориальная Public, Private)

'Peer_Influence' - «Влияние сверстников» (категориальная Positive, Neutral,	Negative)

'Physical_Activity', - «Уровень активность» (количественная)

'Learning_Disabilities', - «Нарушения обучаемости» (категориальная YES, NO)

'Parental_Education_Level' - «Уровень образования родителей» (категориальная High School, College, Postgraduate)

'Distance_from_Home', - «Расстояние от дома» (категориальная Near, Moderate, Far - Ближний, Средний, Дальний)

'Gender', - Пол (категориальная Male, Female)

'Exam_Score' - «Результаты экзаменов» (количественная)

Описательная статистика
"""

df.describe()

"""Студенты в среднем спят по 7 часов

Среднее значение экзаменов 67 баллов, максимальный балл 101, минимальный 55

В данной выборке 235 пропусков (78 пропусков по параметру Teacher_Quality, 90 пропусков по параметру Parental_Education_Level, 67 пропусков по параметру Distance_from_Home) => у 4 студентов учителя и родители без образования
"""

df.describe(include='object')

"""Мужчин - 3814, женщин - 2793

большинство студентов участвую во внеклассных мероприятиях 3938, у 5912 учащихся нет нарушения в обучаемости, 3884 учащихся живут недалеко от школы, 4598 студентов учатся в средней школе, у 2672 учащихся родители имеют низкий доход
"""

quantitative_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include='object').columns.tolist()

print("--- Группировка количественных признаков по категориальным ---")
for cat_col in categorical_cols:
    print(f"\nГруппировка по: {cat_col}")
    grouped_data = df.groupby(cat_col)[quantitative_cols].mean()
    display(grouped_data)
    print("="*50)

"""Для анализа связи между категориальными и количественными переменными, давайте сгруппируем данные по каждой категориальной колонке и вычислим средние значения для всех количественных колонок."""

for cat_col in categorical_cols:
    print(f"\n--- Группировка по: {cat_col} ---")
    grouped_data = df.groupby(cat_col)[quantitative_cols].mean()
    display(grouped_data)
    print("\n" + "="*50 + "\n")

"""Разделим столбцы на категориальные и количественные переменные:"""

plt.figure(figsize=(6,5))
sns.countplot(data=df, x = "Parental_Involvement", palette = "husl")
plt.xticks(rotation=45, ha="right")
plt.xlabel("Участие родителей (низкое, среднее, высокое)")
plt.ylabel("Количество")
plt.title("Распределение участия родителей в образовательном процессе")
plt.show()

df[df['Tutoring_Sessions']==0 & df['Teacher_Quality'].isna()]

df['Tutoring_Sessions'][df['Teacher_Quality'].isna()]

df.isna().sum()

df[df['Teacher_Quality'].isna() & df['Parental_Education_Level'].isna()]

corr = df.corr(numeric_only=True)
plt.figure(figsize=(14, 12))
with sns.axes_style("white"):
  ax = sns.heatmap(corr, annot=True, linewidths=.2, fmt=".2f")
plt.show()

"""Имеется положительная корреляционная зависимость между Результатами экзаменов и Посещаемостью и Результатами экзаменов и Часами обучения"""

fig, axes = plt.subplots(1, 2, figsize=(12, 6))

sns.boxplot(y=df[df['Gender'] == 'Male']['Exam_Score'], ax=axes[0])
axes[0].set_title('Распределение результатов экзаменов для мужчин')
axes[0].set_ylabel('Баллы по экзамену')
axes[0].set_xlabel('Мужчины')

sns.boxplot(y=df[df['Gender'] == 'Female']['Exam_Score'], ax=axes[1])
axes[1].set_title('Распределение результатов экзаменов для женщин')
axes[1].set_ylabel('Баллы по экзамену')
axes[1].set_xlabel('Женщины')

plt.tight_layout()
plt.show()

plt.scatter(df['Hours_Studied'], df['Exam_Score'])
plt.xlabel('Часы обучения')
plt.ylabel('Баллы по экзамену')
plt.show()

plt.scatter(df['Attendance'], df['Exam_Score'])
plt.xlabel('Посещаемость')
plt.ylabel('Баллы по экзамену')
plt.show()

plt.figure(figsize=(8, 6))
sns.stripplot(x='Gender', y='Exam_Score', data=df, jitter=True, hue='Gender', palette='viridis', legend=False)
plt.title('Распределение баллов по экзаменам')
plt.xlabel('Пол')
plt.ylabel('Баллы за экзамен')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Мужчины и женщины имеют одинаковые средние баллы за экзамен. Аномально высокие баллы наблюдаются у женщин"""

sns.boxplot(y = df['Attendance']).set_ylabel("Посещения")

Exam_Score_vs_Teacher_Quality=sns.boxplot(y = df['Exam_Score'], x = df['Teacher_Quality'])
Exam_Score_vs_Teacher_Quality.set_ylabel("Баллы за экзамен")
Exam_Score_vs_Teacher_Quality.set_xlabel("Квалификация учителя")

df_0=df[df['Gender']=='Male']
df_1=df[df['Gender']=='Female']

df_0.hist('Exam_Score', bins=20),df_0.shape

df_1.hist('Exam_Score', bins=20),df_1.shape

"""Среднее значения результатов экзаменов между мужчинами и женщинами не отличается, но у женщин больше представителей с баллами свыше 90"""

df.describe()

df_num = df[['Hours_Studied', 'Attendance', 'Previous_Scores',
        'Sleep_Hours','Tutoring_Sessions', 'Physical_Activity', 'Exam_Score']]

scaler = MinMaxScaler()

X = df_num[['Attendance', 'Hours_Studied', 'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions',
            'Physical_Activity', 'Exam_Score']]

X_norm = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

print("Min-Max Scaled features for clustering (X_norm - first 5 rows):")
display(X_norm.head())

print("\nMin-Max Scaled features for clustering (X_norm - last 5 rows):")
display(X_norm.tail())

d = linkage(X_norm, method='complete')

# Строим дендрограмму
plt.figure(figsize=(9, 6))
dendrogram(d, orientation='top')
plt.title('Дендрограмма для иерархической кластеризации (метод complete)')
plt.xlabel('Индексы объектов или размер кластера')
plt.ylabel('Расстояние (Height)')
plt.show()

d = linkage(X_norm, method='weighted')
plt.figure(figsize=(9, 6))
dendrogram(d, orientation='top')
plt.title('Дендрограмма для иерархической кластеризации (метод weighted)')
plt.xlabel('Индексы объектов или размер кластера')
plt.ylabel('Расстояние (Height)')
plt.show()

d = linkage(X_norm, method='ward')
plt.figure(figsize=(9, 6))
dendrogram(d, orientation='top')
plt.title('Дендрограмма для иерархической кластеризации (метод ward)')
plt.xlabel('Индексы объектов или размер кластера')
plt.ylabel('Расстояние (Height)')
plt.show()

"""Дендограммы построеные по принципами средней связи, варда, cредневзвешенному расстоянию дали четкое разбиение на 3 кластера"""

# создадим пустой список для записи функционала f
f = []
# воспользуемся функцией range(), возвращающей последовательность чисел от 1 до 10
for i in range(1, 11):
    # настроим параметры модели
    kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter = 500, n_init = 10, random_state = 42)
    # обучим модель на нормированных данных для разного числа кластеров
    kmeans.fit(X_norm)
     # для каждого кластера рассчитаем функционал (атрибут inertia_) и поместим в список
    f.append(kmeans.inertia_)
# зададим размер график
plt.figure(figsize = (10,6))
# передадим функции plot() последовательность кластеров и функционал
plt.plot(range(1, 11), f)
# задаем названия графика и осей
plt.title('Выбор оптимального количества кластеров методом локтя')
plt.xlabel('Количество кластеров')
plt.ylabel('Функционал')

"""Метод логтя определил 4 кластера"""

kmeans = KMeans(n_clusters = 4, init = 'k-means++', max_iter = 500, n_init = 10, random_state = 42)
y_pred = kmeans.fit_predict(X_norm)
clusters_1 = kmeans.labels_
df_num['number_KM'] = clusters_1
display(df_num.head())

plt.figure(figsize=(10, 7))
custom_palette = {0: 'red', 1: 'green', 2: 'blue', 3: 'purple'}
sns.scatterplot(x=X_norm['Attendance'], y=X_norm['Exam_Score'], hue=df_num['number_KM'], palette=custom_palette, s=100, alpha=0.7)
plt.title('K-Means')
plt.xlabel('Посещаемость')
plt.ylabel('Баллы за экзамен')
plt.legend(title='Кластер')
plt.grid(True)
plt.show()

df_num['number_KM'].value_counts()

plt.figure(figsize=(10, 7))
custom_palette = {0: 'red', 1: 'green', 2: 'blue', 3: 'purple'}
sns.scatterplot(x=X_norm['Hours_Studied'], y=X_norm['Exam_Score'],
                hue=df_num['number_KM'], palette=custom_palette,
                s=100, alpha=0.7)
plt.title('K-Means')
plt.xlabel('Часы обучения')
plt.ylabel('Баллы за экзамен')
plt.legend(title='Кластер')
plt.grid(True)
plt.show()

"""Путем кластеризаци были получены 4 кластера.

Ученики с высокой посещаемостью кластеры 0 и 3

Ученики с низкой посещаемостью кластеры 1 и 2

Участники 0 и 2 кластера имеют больше учеников с высокими баллами

Ученики из 3 кластера самые неактивные (с маленькими посещаниями и часами обучения)
"""



df_num

plt.figure(figsize=(10, 7))

sns.scatterplot(x=X_norm['Hours_Studied'], y=X_norm['Exam_Score'],
                hue=df_num['number_KM'],
                s=100, alpha=0.7)
plt.title('K-Means')
plt.xlabel('Часы обучения')
plt.ylabel('Баллы за экзамен')
plt.legend(title='Кластер')
plt.grid(True)
plt.show()

"""На рисунке видно, что метод DBScam всех учеников определил в 1 кластер, т.к. большинство учеников имеют средние баллы за экзамен. Метод определил учеников с высокими баллами, как шумовых"""

AggCl = AgglomerativeClustering(n_clusters=4, metric='euclidean', linkage='complete')
y_pred = AggCl.fit_predict(X_norm)
clusters_3 = AggCl.labels_
clusters_3

df_num['number_AC'] = clusters_3
df_num

ac_class_0 = df_num.loc[df_num['number_AC'] == 0]
ac_class_1 = df_num.loc[df_num['number_AC'] == 1]
ac_class_2 = df_num.loc[df_num['number_AC'] == 2]

ac_type_0=ac_class_0.groupby(['number_AC']).agg({'number_AC' : ['count']})
ac_type_1=ac_class_1.groupby(['number_AC']).agg({'number_AC' : ['count']})
ac_type_2=ac_class_2.groupby(['number_AC']).agg({'number_AC' : ['count']})

display(ac_class_0,ac_class_1,ac_class_2)

silhouette_1 = silhouette_score(X_norm, clusters_1)
dbscan = DBSCAN(eps=0.5, min_samples=5) # Default parameters, may need tuning
clusters_2 = dbscan.fit_predict(X_norm)
silhouette_2 = silhouette_score(X_norm, clusters_2)
silhouette_3 = silhouette_score(X_norm, clusters_3)
print('Метрика силуэта (метод к-средних):', silhouette_1.round(3))
print('Метрика силуэта (метод DBSCAN):', silhouette_2.round(3))
print('Метрика силуэта (метод агломеративной кластеризации):', silhouette_3.round(3))

CHS_1 = calinski_harabasz_score(X_norm, clusters_1)
CHS_2 = calinski_harabasz_score(X_norm, clusters_2)
CHS_3 = calinski_harabasz_score(X_norm, clusters_3)
print('Метрика силуэта (метод к-средних):', CHS_1.round(3))
print('Метрика силуэта (метод DBSCAN):', CHS_2.round(3))
print('Метрика силуэта (метод агломеративной кластеризации):', CHS_3.round(3))

DBS_1 = davies_bouldin_score(X_norm, clusters_1)
DBS_2 = davies_bouldin_score(X_norm, clusters_2)
DBS_3 = davies_bouldin_score(X_norm, clusters_3)
print('Метрика силуэта (метод к-средних):', DBS_1.round(3))
print('Метрика силуэта (метод DBSCAN):', DBS_2.round(3))
print('Метрика силуэта (метод агломеративной кластеризации):', DBS_3.round(3))

km_clusters_means = df_num.groupby('number_KM')[['Attendance', 'Hours_Studied',
                                                'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions',
                                                'Physical_Activity', 'Exam_Score']].mean()
display(km_clusters_means)

ac_clusters_means = df_num.groupby('number_AC')[['Attendance', 'Hours_Studied',
                                                'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions',
                                                'Physical_Activity', 'Exam_Score']].mean()
display(ac_clusters_means)

df_num['number_DB'] = clusters_2
db_clusters_means = df_num.groupby('number_DB')[['Attendance', 'Hours_Studied',
                                                'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions',
                                                'Physical_Activity', 'Exam_Score']].mean()
display(db_clusters_means)

"""###Классификация

###3 класса
"""

conditions = [
    df['Exam_Score'] <= 65,
    (df['Exam_Score'] > 65) & (df['Exam_Score'] <= 75),
    df['Exam_Score'] > 75
]
choices = [0, 1, 2]
df['knowledge_assessment'] = np.select(conditions, choices, default=np.nan)
df

df.groupby('knowledge_assessment')['knowledge_assessment'].count()

df_num = df[['Hours_Studied', 'Attendance', 'Sleep_Hours',
       'Previous_Scores',
       'Tutoring_Sessions',
       'Physical_Activity',
       'Exam_Score', 'knowledge_assessment']]

y = df_num['knowledge_assessment']
X = df_num.drop(['knowledge_assessment', 'Exam_Score'], axis=1)

"""###Логистрическая регрессия"""

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)
model = LogisticRegression(solver='liblinear', penalty='l2')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
conf_matr = confusion_matrix(y_test,y_pred)

plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

print(classification_report(y_test, y_pred, target_names=['0','1','2']))

"""Модель достаточно точно предсказывает классы 0 и 1 (низкие и средние баллы за экзамен) т.к. у большинствв студентов баллы за экзамен варируются от 55 до 75. Требует доработки для класса 2 (высокие баллы за экзамен)

###Деревья решений
"""

tree_model = DecisionTreeClassifier(max_depth=4, random_state=0)
tree_model.fit(X_train,y_train)
y_pred_1 = tree_model.predict(X_test)
print(classification_report(y_test,y_pred_1))

export_graphviz(tree_model.fit(X_train, y_train), out_file="tree.dot")
with open("tree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

tree_model_1 = DecisionTreeClassifier(max_depth=10, random_state=0)
tree_model_1.fit(X_train,y_train)
y_pred_1 = tree_model_1.predict(X_test)
print(classification_report(y_test,y_pred_1))
conf_matr = confusion_matrix(y_test,y_pred_1)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

"""Модель переобучилась, метод не подходит для данной выборки.

###Случайный лес
"""

RF_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,          # ограничить глубину деревьев
    min_samples_split=20, # минимум объектов для разбиения узла
    min_samples_leaf=10,  # минимум объектов в листе
    max_features='sqrt',  # меньше признаков на каждое дерево
    random_state=0
)
RF_model.fit(X_train,y_train)
y_pred_2 = RF_model.predict(X_test)
print(classification_report(y_test,y_pred_2))
conf_matr = confusion_matrix(y_test,y_pred_2)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

"""Модель переобучилась, метод не подходит для данной выборки.

###Градиентный бустинг
"""

GB_model = GradientBoostingClassifier(
    n_estimators=100,
    max_depth=3,           # у бустинга деревья должны быть неглубокими
    learning_rate=0.05,    # маленький шаг обучения
    subsample=0.8,         # обучение на подвыборке снижает переобучение
    random_state=0
)
GB_model.fit(X_train,y_train)
y_pred_3 = GB_model.predict(X_test)
print(classification_report(y_test,y_pred_3))
conf_matr = confusion_matrix(y_test,y_pred_3)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

"""Модель переобучилась, метод не подходит для данной выборки.

###Балансировка
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)
ros = RandomOverSampler(random_state=0)
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)

model_up = LogisticRegression(solver='liblinear', penalty='l2')
model_up.fit(X_train_res, y_train_res)
y_up_pred = model_up.predict(X_test)
print(classification_report(y_test,y_up_pred))
conf_matr = confusion_matrix(y_test,y_up_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

"""В ходе балансировки улучшилась полнота класса 2. Показатели модели улучшились

###2 класса
"""

conditions = [
    df['Exam_Score'] <= 70,
    (df['Exam_Score'] > 70)
]
choices = [0, 1]
df['knowledge_assessment'] = np.select(conditions, choices, default=np.nan)
df.groupby('knowledge_assessment')['knowledge_assessment'].count()

df_num = df[['Hours_Studied', 'Attendance', 'Sleep_Hours',
       'Previous_Scores',
       'Tutoring_Sessions',
       'Physical_Activity',
       'Exam_Score', 'knowledge_assessment']]

y = df_num['knowledge_assessment']
X = df_num.drop(['knowledge_assessment', 'Exam_Score'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)
model = LogisticRegression(solver='liblinear', penalty='l2')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
conf_matr = confusion_matrix(y_test,y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

tree_model = DecisionTreeClassifier(max_depth=4, random_state=0)
tree_model.fit(X_train,y_train)
y_pred_1 = tree_model.predict(X_test)
print(classification_report(y_test,y_pred_1))
conf_matr = confusion_matrix(y_test,y_pred_1)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

export_graphviz(tree_model.fit(X_train, y_train), out_file="tree.dot")
with open("tree.dot") as f:
    dot_graph = f.read()
graphviz.Source(dot_graph)

RF_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,
    min_samples_split=20,
    min_samples_leaf=10,
    max_features='sqrt',
    random_state=0
)
RF_model.fit(X_train,y_train)
y_pred_2 = RF_model.predict(X_test)
print(classification_report(y_test,y_pred_2))
conf_matr = confusion_matrix(y_test,y_pred_2)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

GB_model = GradientBoostingClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    random_state=0
)
GB_model.fit(X_train,y_train)
y_pred_3 = GB_model.predict(X_test)
print(classification_report(y_test,y_pred_3))
conf_matr = confusion_matrix(y_test,y_pred_3)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)
ros = RandomOverSampler(random_state=0)
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)
model_up = LogisticRegression(solver='liblinear', penalty='l2')
model_up.fit(X_train_res, y_train_res)
y_up_pred = model_up.predict(X_test)
print(classification_report(y_test,y_up_pred))
conf_matr = confusion_matrix(y_test,y_up_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_matr, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Предсказанное значение')
plt.ylabel('Фактическое значение')
plt.title('Матрица ошибок')

"""Как и в случае с тремя классами наблюдается несбалансированное состояние данных и переобучение моделей деревьев решений, случайного леса, градиентоного бустинга. Как и в прошлом случае, балансировка балансировка способствовала улучшению показателей модели"""